/:
  controller: Base
  action: index

/contact:
  controller: Base
  action: contact

/mon-super-portfolio:
  controller: Base
  action: portfolio

/login:
  controller: Auth
  action: login

/logout:
    controller: Auth
    action: logout

/register:
  controller: Auth
  action: register

/cree-page:
  controller: PageController
  action: insert

/index-page:
  controller: PageController
  action : index

/supprime-page:
  controller: PageController
  action: delete

/publication:
  controller: PageController
  action: publication

/update-page:
  controller: PageController
  action: update

/creer-article:
  controller: ArticleController
  action: insert