/:
  controller: Base
  action: index

/login:
  controller: Auth
  action: login

/dashboard:
  controller: Auth
  action: dashboard

/register:
  controller: Auth
  action: register

/password-reset:
  controller: Auth
  action: passwordReset

/reset-password:
  controller: Auth
  action: resetPasswordForm

/logout:
  controller: Auth
  action: logout

/verify-email:
  controller: Auth
  action: verifyEmail

/check-password:
  controller: Auth
  action: checkPassword

/debug-db:
  controller: Auth
  action: debugDb

/cree-page:
  controller: PageController
  action: insert

/index-page:
  controller: PageController
  action : index

/supprime-page:
  controller: PageController
  action: delete

/publication:
  controller: PageController
  action: publication

/update-page:
  controller: PageController
  action: update

/users-management:
  controller: Auth
  action: usersManagement

/edit-user:
  controller: Auth
  action: editUser

/delete-user:
  controller: Auth
  action: deleteUser

/creer-article:
  controller: ArticleController
  action: insert